public with sharing class AssignmentCaseTriggerHandler {
    // public AssignmentCaseTriggerHandler() {}

    // /**
    //  * Create new AssignmentCase__c records
    //  * @Return void
    //  */
    // public static void onNewAssignmentCase(List<Case> newCases) {
    //     List<AssignmentCase__c> newAssignmentCases = new List<AssignmentCase__c>();
    //     try {
    //         // Create new AssignmentCase__c records for each new Case
    //         for (Case c : newCases) {
    //             newAssignmentCases.add(new AssignmentCase__c(Case__c = c.id));
    //         }

    //         System.debug('newAssignmentCases: ' + newAssignmentCases);
    //         insert newAssignmentCases;
    //     } catch (Exception e) {
    //         System.debug('Error: ' + e.getMessage());
    //     }
        
    // }
}